apiVersion: v1
kind: Pod
metadata:
  name: privileged-test-pod
  labels:
    app: privileged-test
spec:
  containers:
  - name: privileged-container
    image: nginx
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - ALL
    volumeMounts:
      - mountPath: /host
        name: host-root
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory
